# This version should be updated whenever there is a change that makes this version of kani
# incompatible with the verify-std repo.

[kani]
commit = "8400296f5280be4f99820129bc66447e8dff63f4"

# Temporarily track CBMC version with spurious CEX fix
[cbmc]
commit = "83f61a4127f9b2f8fcd45993dfe9a9fbecc362e1"
